#!/bin/bash

if ! (( 1 == $# ))
then
    echo "Usage: $0 fib|sh" >&2
    exit 2
fi

case $1 in
    fib ) class=matrix.Mathik ;;
    sh ) class=shell.Shell ;;
    * ) echo "Usage: $0 fib|sh" >&2 ; exit 2 ;;
esac

exec ./mvnw -q -DskipTests -Djansi.passthrough=true package exec:java -Dexec.mainClass=hm.binkley.labs.skratch.math.${class}Kt
