#!/bin/bash

function usage {
    echo "Usage: $0 fib|sh"
}

if ! (( 1 == $# ))
then
    usage >&2
    exit 2
fi

case $1 in
    fib ) class=matrix.Mathik ;;
    sh ) class=shell.Shell ;;
    * ) usage >&2 ; exit 2 ;;
esac

exec ./mvnw -q -DskipTests -Djansi.passthrough=true package exec:java -Dexec.mainClass=hm.binkley.labs.skratch.math.${class}Kt
